### ISSUE TITLE
Copyrighted commercial font files appear improperly licensed for distribution

### ISSUE THREAD

**Issue by Nandini-WoW** [TekNoLogic/tekticles#1]
<p>This analysis is based on the <b>3.0.9.9-Release</b> version of the <b>Tekticles</b> addon.</p>

<blockquote>This table lists font files discovered in the addon, their MD5 hashes, and the specific versions of fonts they were matched to. Following the table is a discussion of individual fonts or families and their licensing implications for the way they are distributed with this addon.</blockquote>

<table>
<tr>
<td><b>filePath</b></td>
<td><b>fileName</b></td>
<td><b>fileMD5</b></td>
<td><b>fontName</b></td>
<td><b>fontVersion</b></td>
<td><b>fontCopyright</b></td>
<td><b>fontCost</b></td>
<td><b>fontDesigner</b></td>
</tr>
<tr>
<td>Tekticles\</td>
<td>Calibri.ttf</td>
<td>d5630a8814488c1800727da51c00c256</td>
<td>Calibri</td>
<td>1.0</td>
<td>&copy; 2005 Microsoft Corporation. All Rights Reserved.</td>
<td>commercial</td>
<td>Microsoft</td>
</tr>
<tr>
<td>Tekticles\</td>
<td>CalibriBold.ttf</td>
<td>852368cbd386a86d96ffa4dfffc866d5</td>
<td>Calibri Bold</td>
<td>1.0</td>
<td>&copy; 2005 Microsoft Corporation. All Rights Reserved.</td>
<td>commercial</td>
<td>Microsoft</td>
</tr>
<tr>
<td>Tekticles\</td>
<td>CalibriBoldItalic.ttf</td>
<td>8248d1bb7b4215035bb019bfb0069e2d</td>
<td>Calibri Bold Italic</td>
<td>1.0</td>
<td>&copy; 2005 Microsoft Corporation. All Rights Reserved.</td>
<td>commercial</td>
<td>Microsoft</td>
</tr>
<tr>
<td>Tekticles\</td>
<td>CalibriItalic.ttf</td>
<td>8e3102aba109df772446d70df88c918d</td>
<td>Calibri Italic</td>
<td>1.0</td>
<td>&copy; 2005 Microsoft Corporation. All Rights Reserved.</td>
<td>commercial</td>
<td>Microsoft</td>
</tr>
</table>

<h2>Discussion</h2>

<p><b>Calibri by Microsoft</b></p>

<blockquote>This is a successful commercial font Microsoft distributes with Office 2007 and Windows Vista. The EULAs for both of these fonts do not allow them to be distributed in an unlimited manner such as with an addon. Information for licensing a current version of these fonts for distribution with software can be found at the <a href="http://www.microsoft.com/typography/fonts/family.aspx?FID=287">Microsoft typography</a> website. If this proves to be cost prohibitive, the author should probably stop distributing these fonts with the addon.</blockquote>

**Comment by tekkub** [comment]
Yup.  No, I have no plans on changing it :P

**Comment by Nandini-WoW** [comment]
You do realize that the font's designer isn't a rock star; he's a teacher at a university in the Netherlands. When you distribute his fonts this way, he isn't getting royalties for his creative work.

Edit: Turns out he is teaching in Germany now.

**Comment by tekkub** [comment]
"Calibri by Microsoft" doesn't say to me "this font was designed by a teacher" :P

And, uhm, I don't get royalties for my creative work either, so you know, not much sympathy here.  Would it make you feel better if I put a note that said you should only use this addon if you're on Vista, since then you already have the fonts?

**Comment by Nandini-WoW** [comment]
I realize you don't get royalties. However, you do have a donation button on every site where you distribute this addon. Where's Lucas de Groot's button? Where's Microsoft's?

I'm not asking for your sympathy. I'm just trying to point out to you that this font is software made up of code and data, just like your addon. It's copyrighted. It requires a license for use and distribution. This license also happens to cost money, in this case.

I noticed you made a new, special (and subversive) build of tekticles last night for WowMatrix users. This leads me to believe that as an author, you appear care about your right to have your work distributed in a manner you see fit. I'm only asking that you give the same consideration to distributing someone else's creative work in whole within your own addon.

**Comment by tekkub** [comment]
I do, but... engh, it's MS.  MS is a big huge grey area for me, I don't pay for their stuff, I haven't for years, and I'm not highly compelled to change my ways.  Plus I'm a stubborn fuck.

How about this, got any fonts that look as good in-game that are free?  I'm not against changing things, I'm just lazy and picky, and these fonts look damn good.

**Comment by Nandini-WoW** [comment]
I know they look great! A lot of the reason for this is because Lucas spent almost 3 years perfecting this font family. (Its design is closely related to Consolas, which is a great monospace font for coding, too!)

I've been searching for a nice open license (or freely licensed) alternative to Calibri for months now and haven't found anything quite of the same quality yet.

There are a couple open license fonts that do come pretty close, and don't look bad at all in WoW, thought they don't have Calibri's distinctive beauty. One that comes close is DejaVu Sans (http://dejavu-fonts.org/wiki/index.php?title=Main_Page). It also comes with a particularly readable condensed style which might work well for chat boxes, numbers, etc.
