### ISSUE TITLE
tekticles 3.3.0.11 error: PlayerTitleFrame_UpdateTitles is not a function

### ISSUE THREAD

**Issue by jasonwmatteson** [TekNoLogic/tekticles#10]
Date: 2012-03-27 07:53:12
ID: 1
Error occured in: Global
Count: 3
Message: ..\AddOns\tekticles\tekticles.lua line 83:
   hooksecurefunc(): PlayerTitleFrame_UpdateTitles is not a function
Debug:

   tekticles\tekticles.lua:83:
      tekticles\tekticles.lua:13
AddOns:
  Swatter, v3.2.4 (<%codename%>)
  NPCScan, v4.3.0.2
  ACP, v3.3.17 
  ArkInventory, v3.02
  ArkInventoryRules, v
  Auctionator, v3.0.0
  Babylonian, v5.1.DEV.312(/embedded)
  Bartender4, v4.4.20.1
  ButtonFacade, v4.3.378
  Configator, v5.1.DEV.312(/embedded)
  EasyMD, v0.4
  Gatherer, v3.2.4
  GathererDBWowhead, v1.0.2011-11-03
  kgPanels, v1.7
  Mapster, v1.4.3
  Masque, v4.3.378
  MasqueSleek, v4.3.0
  MasqueTrinity, v40300.1
  MoncaiQuestTracker, v4.3.0-beta
  Omen, v3.1.6
  Postal, v3.4.13
  PowerAuras, v4.23
  Quartz, v3.0.8
  QuestHubber, v
  QuestHubberAzeroth, v
  QuestHubberCataclysm, v
  QuestHubberDaily, v
  QuestHubberNorthrend, v
  QuestHubberOutland, v
  Recount, v
  SellJunk, v3.0.4
  ShadowedUnitFrames, vv3.4.4
  SlideBar, v3.2.4 (<%codename%>)
  TattooMinimap, v000010
  tekticles, v3.3.0.11
  TipTac, v10.12.05
  TipTacItemRef, v10.12.06
  TipTacTalents, v10.11.23
  BlizRuntimeLib_enUS v4.3.3.40300 <us>
  (ck=3a7)

I am running latest WOW build, Windows 7, 64-bit and the 64-bit WOW client.

**Comment by tekkub** [comment]
Update your addon, this was fixed long ago.

**Comment by jasonwmatteson** [comment]
my mistake....Curse and WowMatrix only have 3.3.0.11. Thanks for he add on!
