### ISSUE TITLE
Tekticles error (PlayerTitleFrame_UpdateTitles is not a function)

### ISSUE THREAD

**Issue by instamat** [TekNoLogic/tekticles#11]
Here is the error message:

Date: 2012-08-05 14:14:20
ID: 1
Error occured in: Global
Count: 2
Message: ..\AddOns\tekticles\tekticles.lua line 83:
   hooksecurefunc(): PlayerTitleFrame_UpdateTitles is not a function
Debug:

```
  [string "*:OnLoad"]:1
```

   tekticles\tekticles.lua:83:
      tekticles\tekticles.lua:13
AddOns:
  MoncaiCompare, v1.4.3
  Swatter, v5.13.5258 (BoldBandicoot)
  WowheadLooter, v40020
  NPCScan, v4.3.0.2
  NPCScanOverlay, v4.3.0.1
  Ace2, v
  Ace3, v
  ACP, v3.3.17 
  AdiBags, vv1.4.7.1
  AdvancedIconSelector, v1.0.4
  AdvancedTradeSkillWindow, v
  Align, v
  Altoholic, v4.3.003
  Archy, v1.8.24
  AtlasLootLoader, vv6.05.04
  AucAdvanced, v5.13.5258 (BoldBandicoot)
  AucFilterBasic, v5.13.5258 (BoldBandicoot)
  AucFilterOutlier, v5.13.5258.5187(5.13/embedded)
  AucMatchUndercut, v5.13.5258.5232(5.13/embedded)
  AucStatHistogram, v5.13.5258 (BoldBandicoot)
  AucStatiLevel, v5.13.5258 (BoldBandicoot)
  AucStatPurchased, v5.13.5258 (BoldBandicoot)
  AucStatSales, v5.13.5258.4838(5.13/embedded)
  AucStatSimple, v5.13.5258 (BoldBandicoot)
  AucStatStdDev, v5.13.5258 (BoldBandicoot)
  AucStatWOWEcon, v5.13.5258.4828(5.13/embedded)
  AucUtilAHWindowControl, v5.13.5258.5133(5.13/embedded)
  AucUtilAppraiser, v5.13.5258.5241(5.13/embedded)
  AucUtilAskPrice, v5.13.5258.5160(5.13/embedded)
  AucUtilAutoMagic, v5.13.5258.5224(5.13/embedded)
  AucUtilCompactUI, v5.13.5258.5254(5.13/embedded)
  AucUtilEasyBuyout, v5.13.5258.5241(5.13/embedded)
  AucUtilFixAH, v5.13.5258 (BoldBandicoot)
  AucUtilItemSuggest, v5.13.5258.5224(5.13/embedded)
  AucUtilPriceLevel, v5.13.5258.5241(5.13/embedded)
  AucUtilScanButton, v5.13.5258.5153(5.13/embedded)
  AucUtilScanFinish, v5.13.5258.5153(5.13/embedded)
  AucUtilScanProgress, v5.13.5258.4979(5.13/embedded)
  AucUtilScanStart, v5.13.5258.5153(5.13/embedded)
  AucUtilSearchUI, v5.13.5258.5254(5.13/embedded)
  AucUtilSimpleAuction, v5.13.5258.5210(5.13/embedded)
  AucUtilVendMarkup, v5.13.5258.4828(5.13/embedded)
  Auctionator, v3.0.0
  Aurora, v3.9a
  AutoBar, vv4.3.0.04
  AutoRepair, v
  AutoTabard, v1.972
  Babylonian, v5.1.DEV.312(/embedded)
  BeanCounter, v5.13.5258 (BoldBandicoot)
  ButtonFacade, v4.3.382
  CallbackHandler10, v
  CameraDistanceMaxFactor, v1.0
  Chatter, v1.0
  Chinchilla, vv2.5.3
  Clique, vv40300-1.5.2
  Configator, v5.1.DEV.312(/embedded)
  DataStore, v4.3.001
  DataStoreAchievements, v4.3.001
  DataStoreAgenda, v4.3.001
  DataStoreAuctions, v4.3.001
  DataStoreCharacters, v4.3.001
  DataStoreContainers, v4.3.001
  DataStoreCrafts, v4.3.001
  DataStoreCurrencies, v4.3.001
  DataStoreInventory, v4.3.001
  DataStoreMails, v4.3.001
  DataStorePets, v4.3.001
  DataStoreQuests, v4.3.001
  DataStoreReputations, v4.3.001
  DataStoreSpells, v4.3.001
  DataStoreStats, v4.3.001
  DataStoreTalents, v4.3.001
  DBMCore, v
  DebugLib, v5.1.DEV.312(/embedded)
  DKPProfiler, v0.703
  Dominos, v4.3.4
  DominosBufftimes, v
  DominosCast, v
  DominosRoll, v
  DominosTotems, v
  DominosXP, v
  DugisGuideViewerZ, v5.6140
  Enchantrix, v5.13.5258 (BoldBandicoot)
  EnchantrixBarker, v5.13.5258 (BoldBandicoot)
  Factionizer, v4.3.0
  ForteCasting, v
  ForteClass, v
  ForteCooldown, v
  ForteCore, v1.976.2
  ForteHealthstone, v
  ForteSoulstone, v
  ForteSummon, v
  ForteTalent, v
  ForteTimer, v
  Gatherer, v3.2.4
  GathererDBWowhead, v1.0.2009-02-18
  GreenWall, v1.2.2
  Grid, v4.3.4.1485-beta
  GupPet, v2.021
  GupPetButtonFacade, v0.2
  GupPetCollectMe, v2.01
  Informant, v5.13.5258 (BoldBandicoot)
  JPack, v0.7.11
  JPackBroker, v
  JPackEx, v
  Juggler, v4.3.0.1
  LibAboutPanel, v1.5
  LibExtraTip, v5.12.DEV.319(/embedded)
  LibSharedMedia30, v3.0-69
  LibSink20, v
  LibStub, v
  LilSparkysWorkshop, v
  MacroBank, v1.10
  MarketWatcher, v2.14
  Masque, v4.3.382
  MasqueDarion, v4.1.2
  MasqueEntropy, v4.3.73
  MasqueLiteStep, v4.3.61
  MasqueRenaitre, vv4.3.4
  MasqueTones, v4.3.0
  MinimapButtonFrame, v3.1.7
  MinimapButtonFrameSkinPack, v3.0
  Name2Face, vv1.5 build 201208010500
  OgriLazy, v1.1.0
  OmniCC, v4.3.2
  OpenRaid, v
  oRA3, v
  Postal, v3.4.13
  PowerAuras, v4.23
  RatingBuster, v1.6.7
  Recount, v
  Routes, vv1.4.2
  SellOMatic, vl02
  SharedMedia, v3.0.4-179
  SlideBar, v5.13.5258 (BoldBandicoot)
  Stubby, v5.13.5258 (BoldBandicoot)
  tekticles, v3.3.0.11
  TidyPlates, v6.6.1 (R4xx)
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesThreatPlates, v5.5
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.315(/embedded)
  TipTac, v12.05.20
  TipTacItemRef, v12.05.20
  TipTacTalents, v12.05.20
  TomTom, vv40300-1.4.5
  TradeSkillMaster, vv1.3.2
  TradeSkillMasterAuctionDB, vv1.2
  TradeSkillMasterAuctioning, vv1.1.7
  TradeSkillMasterCrafting, vv1.1.1
  TradeSkillMasterMailing, vv1.0.2
  TradeSkillMasterShopping, vv1.2.2
  VendorBait, v4.2.0.8
  XPerl, v3.2.1
  XPerlArcaneBar, v
  XPerlParty, v
  XPerlPartyPet, v
  XPerlPlayer, v
  XPerlPlayerBuffs, v
  XPerlPlayerPet, v
  XPerlRaidAdmin, v
  XPerlRaidFrames, v
  XPerlRaidHelper, v
  XPerlRaidPets, v
  XPerlTarget, v
  XPerlTargetTarget, v
  BlizRuntimeLib_enUS v4.3.4.40300 <us>
  (ck=12d5)

**Comment by tekkub** [comment]
You have an old version of this addon.

**Comment by instamat** [comment]
More like a REALLY old version! Thank you. :D
