### ISSUE TITLE
Nameplate text missing in 5.4.2

### ISSUE THREAD

**Issue by MeatyChunks** [TekNoLogic/tekticles#13]
Hi there! With nameplates enabled any of the text such as name and level are missing. I disabled all other addons to confirm it was just tekticles.

![20131211110138153](https://f.cloud.github.com/assets/6160351/1723220/03567d1a-6254-11e3-8913-c7ab8fa53206.png)

Really appreciate your wow addons. Thanks a lot!

**Comment by MeatyChunks** [comment]
Ah I found this post which fixes it for now atleast:

"For those using tekticles, open the file tekticles.lua in the addon's folder, and search for and replace the following line:

NAMEPLATE_FONT = BOLD

with:

SetFont(GameFontWhite, BOLD, 13)

From what I can tell, the constant NAMEPLACE_FONT used to refer to a font path, while it now refers to the GameFontWhite font element since 5.4.2."

Thanks again for your hard work!

**Comment by tekkub** [comment]
Fixed in 9987a8ab698f3e2b6165559c3709051083700f80
