### ISSUE TITLE
Tekticles issue with Glpyh Pane.

### ISSUE THREAD

**Issue by Badgob** [TekNoLogic/tekticles#5]
Apparently, if you attempt to inscribe a glyph, tekticles gets blocked but the UI. Here is my taintlog:

12/1 00:55:31.028  Global variable COMBAT_TEXT_X_SCALE tainted by tekticles - Interface\AddOns\Blizzard_CombatText\Blizzard_CombatText.lua:571 CombatText_UpdateDisplayedMessages()
12/1 00:55:31.028      Interface\FrameXML\InterfaceOptionsPanels.lua:1413
12/1 00:55:31.028  Execution tainted by tekticles while reading COMBAT_TEXT_X_SCALE - Interface\AddOns\Blizzard_CombatText\Blizzard_CombatText.lua:395
12/1 00:55:31.028  An action was blocked because of taint from tekticles - CastGlyph()
12/1 00:55:31.028      Interface\AddOns\Blizzard_GlyphUI\Blizzard_GlyphUI.lua:580 GlyphFrameSpell_OnClick()
12/1 00:55:31.028      GlyphFrameScrollFrameButton4:OnClick()
12/1 00:55:35.985  Global variable COMBAT_TEXT_X_SCALE tainted by tekticles - Interface\AddOns\Blizzard_CombatText\Blizzard_CombatText.lua:571 CombatText_UpdateDisplayedMessages()
12/1 00:55:35.985      Interface\FrameXML\InterfaceOptionsPanels.lua:1413
12/1 00:55:35.985  Execution tainted by tekticles while reading COMBAT_TEXT_X_SCALE - Interface\AddOns\Blizzard_CombatText\Blizzard_CombatText.lua:395
12/1 00:55:35.985  An action was blocked because of taint from tekticles - CastGlyph()
12/1 00:55:35.985      Interface\AddOns\Blizzard_GlyphUI\Blizzard_GlyphUI.lua:580 GlyphFrameSpell_OnClick()
12/1 00:55:35.985      GlyphFrameScrollFrameButton4:OnClick()
12/1 01:12:05.935  Global variable COMBAT_TEXT_X_SCALE tainted by tekticles - Interface\AddOns\Blizzard_CombatText\Blizzard_CombatText.lua:571 CombatText_UpdateDisplayedMessages()
12/1 01:12:05.935      Interface\FrameXML\InterfaceOptionsPanels.lua:1413
12/1 01:12:05.935  Execution tainted by tekticles while reading COMBAT_TEXT_X_SCALE - Interface\AddOns\Blizzard_CombatText\Blizzard_CombatText.lua:395
12/1 01:12:05.935  An action was blocked because of taint from tekticles - CastGlyph()
12/1 01:12:05.935      Interface\AddOns\Blizzard_GlyphUI\Blizzard_GlyphUI.lua:580 GlyphFrameSpell_OnClick()
12/1 01:12:05.935      GlyphFrameScrollFrameButton4:OnClick()

**Comment by tekkub** [comment]
I never touch `COMBAT_TEXT_X_SCALE`.  I also have no taint issues here when casting glyphs.  Can you disable all addons but tekticles and test again?
