### ISSUE TITLE
Lua issues with 4.1 patch

### ISSUE THREAD

**Issue by ghost** [TekNoLogic/tekticles#7]
Hi,

I got the following lua error with tekticles 3.3.0.11 and patch 4.1, released on April 26, 2011:

3x tekticles\tekticles-3.3.0.11-Release.lua:83: hooksecurefunc(): PlayerTitleFrame_UpdateTitles is not a function
<in C code>
tekticles\tekticles-3.3.0.11-Release.lua:83: in function <tekticles\tekticles.lua:13>

Locals:
NORMAL = "..\Calibri.ttf"
BOLD = "..\CalibriBold.ttf"
BOLDITALIC = "..\CalibriBoldItalic.ttf"
ITALIC = "..\CalibriItalic.ttf"
NUMBER = "..\CalibriBold.ttf"
FixTitleFont = <func> @..\tekticles.lua:82
SetFont = <func> @..\tekticles.lua:2

**Comment by tekkub** [comment]
Already fixed in 58ac37fe1cd56279ebdf83c2825dd4d178a9713c
