### ISSUE TITLE
Lua error in patch 4.2`

### ISSUE THREAD

**Issue by Lyssanne** [TekNoLogic/tekticles#8]
I am getting the following lua error in 4.2:  (it looks like when I attempted to copy the text I didn't grab the bottom portion...I will install a buggrabber addon and post again if this isn't enough info to fix the bug)

Message: Interface\AddOns\tekticles\tekticles.lua:83: hooksecurefunc(): PlayerTitleFrame_UpdateTitles is not a function
Time: 07/05/11 18:15:28
Count: 1
Stack: [C](?): in function `hooksecurefunc'
Interface\AddOns\tekticles\tekticles.lua:83: in function <Interface\AddOns\tekticles\tekticles.lua:13>
[C]: in function`LoadAddOn'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:7: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>

[C](?): in function `hooksecurefunc'
Interface\AddOns\tekticles\tekticles.lua:83: in function <Interface\AddOns\tekticles\tekticles.lua:13>

Locals:

**Comment by Lyssanne** [comment]
Actually, there was nothing after "Locals:"...sorry for the confusion.

**Comment by tekkub** [comment]
What version do you have?

**Comment by Lyssanne** [comment]
3.3.0.11-Release...and I just noticed that there has been a beta update
since then.  I'm really sorry - I had the curse client only tagged to update
releases for most addons, and I didn't have tekticles "favorited" on WoW
Interface because it was available on the Curse Client...crap. I will update
and let you know if the error still occurs.  Thank you very much.
